name: Floorsheet Data Auto Scrape

on:
  push:
    branches:
      - master
  schedule:
    - cron: '20 20 * * *' # 11:20am UTC => 05:00pm Nepal Time

jobs:

  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout 
        uses: actions/checkout@v2

      - name: Setup Python Environment
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
      
      - name: Install Dependencies
        run: |
          pip install -r requirements.txt
      
      - name: Execute Scraping Script
        run: |
          python scrape_nepse.py

      - name: Check if CSV file exists
        id: check_csv
        run: |
          if [ -f "./floorsheets_test/$(date +'%Y-%m-%d').gz" ]; then
            echo "CSV file exists"
            echo "::set-output name=csv_exists::true"
          else
            echo "CSV file does not exist"
            echo "::set-output name=csv_exists::false"
            exit 0 # don't show error
            
          fi

      - name: Commit and Push Files
        if: steps.check_csv.outputs.csv_exists == 'true'
        run: |
           git config --local user.email "robinnarsingha123@gmail.com"
           git config --local user.name "robinnarsinghranabhat"        
           git add .
           git commit -am "Floorsheet data scrapped successfully"
           git push origin master
